version: '3'

networks:
  web:
    external: true

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    ports:
      - "8080:80"
    restart: always
